// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbg_vWsQaoBZavBZ4UbdM91qtmMlZDDvk',
    appId: '1:304151548501:web:edcdc26161720c56357adc',
    messagingSenderId: '304151548501',
    projectId: 'app-gastos-f1b62',
    authDomain: 'app-gastos-f1b62.firebaseapp.com',
    storageBucket: 'app-gastos-f1b62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeEh7GreBCvlkvZG59gnx7sNeB0ArDyhs',
    appId: '1:304151548501:android:ac2c187d90765e2b357adc',
    messagingSenderId: '304151548501',
    projectId: 'app-gastos-f1b62',
    storageBucket: 'app-gastos-f1b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADmy4nw7mf4twX8xki0bThwObF4hcuF74',
    appId: '1:304151548501:ios:c3656f2c93568eff357adc',
    messagingSenderId: '304151548501',
    projectId: 'app-gastos-f1b62',
    storageBucket: 'app-gastos-f1b62.appspot.com',
    iosBundleId: 'com.example.appGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADmy4nw7mf4twX8xki0bThwObF4hcuF74',
    appId: '1:304151548501:ios:c3656f2c93568eff357adc',
    messagingSenderId: '304151548501',
    projectId: 'app-gastos-f1b62',
    storageBucket: 'app-gastos-f1b62.appspot.com',
    iosBundleId: 'com.example.appGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbg_vWsQaoBZavBZ4UbdM91qtmMlZDDvk',
    appId: '1:304151548501:web:1ec5000c3772ad89357adc',
    messagingSenderId: '304151548501',
    projectId: 'app-gastos-f1b62',
    authDomain: 'app-gastos-f1b62.firebaseapp.com',
    storageBucket: 'app-gastos-f1b62.appspot.com',
  );

}